name: xargofloat
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  - ipykernel
  # Examples (remove and add as needed)
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - astropy # eliminate once the dependecy is not strict upstream in xarrayutils anymore
  - pip
  - pip:
    - git+https://github.com/jbusecke/xarrayutils.git
